# Generated by Django 3.2.4 on 2021-06-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'T-Shirt'), ('M', 'T-Shirt'), ('L', 'T-Shirt'), ('XL', 'T-Shirt')], default='test descriptions', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='test', max_length=230),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('SP', 'SportsWear'), ('WW', 'WinterWear'), ('SW', 'SummerWear'), ('CW', 'CasualWear')], default='CW', max_length=2),
            preserve_default=False,
        ),
    ]
